export const themeColors = {
  light: {
    accent: "#DC2626",
    accentDark: "#B91C1C",
    accentLight: "#FFF1F2",
    background: "#FFFFFF",
    border: "#E2E8F0",
    ink: "#0F172A",
    muted: "#64748B",
    surface: "#FFFFFF",
    surfaceMuted: "#F8FAFC",
    success: "#15803D",
    warning: "#B45309",
    notificationEmergency: "#B45309",
    notificationEmergencyBg: "#FEF3C7",
    notificationApproval: "#15803D",
    notificationApprovalBg: "#DCFCE7",
    notificationRejection: "#DC2626",
    notificationRejectionBg: "#FEE2E2",
    notificationInventory: "#2563EB",
    notificationInventoryBg: "#DBEAFE",
    notificationSystem: "#64748B",
    notificationSystemBg: "#F1F5F9",
  },
  dark: {
    accent: "#EF4444",
    accentDark: "#F87171",
    accentLight: "#1A0505",
    background: "#060910",
    border: "#1E293B",
    ink: "#F8FAFC",
    muted: "#94A3B8",
    surface: "#0D1117",
    surfaceMuted: "#111827",
    success: "#4ADE80",
    warning: "#FBBF24",
    notificationEmergency: "#FBBF24",
    notificationEmergencyBg: "#78350F",
    notificationApproval: "#4ADE80",
    notificationApprovalBg: "#14532D",
    notificationRejection: "#F87171",
    notificationRejectionBg: "#7F1D1D",
    notificationInventory: "#60A5FA",
    notificationInventoryBg: "#1E3A8A",
    notificationSystem: "#94A3B8",
    notificationSystemBg: "#1E293B",
  },
} as const;

export type ThemeColors = (typeof themeColors)[keyof typeof themeColors];
