#!/usr/bin/env node
/**
 * Dev-only helper: writes a git-ignored `.env` pointing the mobile app at the
 * backend running on this PC, using the PC's current Wi-Fi IPv4 — so a physical
 * Android phone on the same network can reach it without you hand-editing the
 * file every time your LAN IP changes.
 *
 * No production concern: this only touches the local, git-ignored `.env`.
 * Production apps read their real EXPO_PUBLIC_API_URL from the build environment
 * and never run this script.
 *
 * Usage:  npm run dev:setup   (then  npx expo start --clear)
 */
const os = require("os");
const fs = require("fs");
const path = require("path");

const PORT = 5000;

/** Picks the most likely Wi-Fi/Ethernet IPv4 the phone can reach. */
function pickLanIpv4() {
  const interfaces = os.networkInterfaces();
  const candidates = [];
  for (const [name, addrs] of Object.entries(interfaces)) {
    if (!addrs) continue;
    for (const addr of addrs) {
      if (addr.family !== "IPv4" || addr.internal) continue;
      // Prefer common physical/virtual adapter names; 192.168.* / 10.* / 172.16-31.*
      // are the private ranges a phone on the same LAN will route to.
      if (/^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)/.test(addr.address)) {
        const score =
          (/wi-?fi|wireless|wlan|wi0|en0|eth0/i.test(name) ? 2 : 0) +
          (/virtual|hyper-v|vethernet|vmware|wsl|docker/i.test(name) ? -1 : 0);
        candidates.push({ address: addr.address, score });
      }
    }
  }
  if (candidates.length === 0) return null;
  candidates.sort((a, b) => b.score - a.score);
  return candidates[0].address;
}

const ip = pickLanIpv4();
if (!ip) {
  console.error(
    "[dev:setup] Could not detect a private IPv4 on a physical adapter.\n" +
      "Make sure you're connected to Wi-Fi, then re-run, or set EXPO_PUBLIC_API_URL manually in .env.",
  );
  process.exit(1);
}

const envPath = path.join(__dirname, "..", ".env");
const apiUrl = `http://${ip}:${PORT}/api`;

const content = `# Local development environment for BloodLink Mobile.
# Auto-generated by scripts/setup-dev-env.cjs (npm run dev:setup).
# This file is git-ignored (see .gitignore) — never commit real values.
#
# Current PC LAN IPv4: ${ip} (re-run \`npm run dev:setup\` when this changes).
# Web runs on this same PC and can reach this address too; the mobile app on a
# phone over Wi-Fi must use the LAN IP (it cannot reach the PC's "localhost").
EXPO_PUBLIC_API_URL=${apiUrl}

# Optional: Google Maps Android API key for the embedded "Nearby" map.
EXPO_PUBLIC_GOOGLE_MAPS_ANDROID_API_KEY=
`;

fs.writeFileSync(envPath, content, { mode: 0o600 });
console.log(`[dev:setup] Wrote .env → EXPO_PUBLIC_API_URL=${apiUrl}`);
console.log("[dev:setup] Now run:  npx expo start --clear");
