import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AdminAccess } from "../../src/components/AdminAccess";
import { AppScreen, Surface } from "../../src/components/AppScreen";
import { adminService } from "../../src/services/adminService";
import { apiClient } from "../../src/services/apiClient";
import { spacing } from "../../src/theme/spacing";
import { useThemeColors } from "../../src/theme/useThemeColors";
import type { HospitalResponse } from "../../src/types/location";
import type { HospitalInput } from "../../src/types/userFeatures";
import { getApiErrorMessage } from "../../src/utils/apiError";

const blank: HospitalInput = { name: "", address: "", state: "", district: "", phone: "" };
export default function AdminHospitalsScreen() { const colors = useThemeColors(); const [hospitals, setHospitals] = useState<HospitalResponse[]>([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState<HospitalInput | null>(null); const [editing, setEditing] = useState<HospitalResponse | null>(null); const load = useCallback(async () => { await Promise.resolve(); setLoading(true); try { setHospitals(await apiClient.getHospitals()); } catch (e) { Alert.alert("Unable to load hospitals", getApiErrorMessage(e)); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]); const save = async () => { if (!form) return; if (Object.values(form).some((value) => typeof value === "string" && !value.trim()) || !/^\d{10}$/.test(form.phone)) { Alert.alert("Check hospital details", "Enter all fields and a 10-digit phone number."); return; } try { const saved = editing ? await adminService.updateHospital(editing._id, form) : await adminService.createHospital(form); setHospitals((current) => editing ? current.map((item) => item._id === saved._id ? saved : item) : [saved, ...current]); setForm(null); setEditing(null); } catch (e) { Alert.alert("Unable to save hospital", getApiErrorMessage(e)); } }; const remove = (hospital: HospitalResponse) => Alert.alert("Delete hospital?", `${hospital.name} will be removed.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void adminService.deleteHospital(hospital._id).then(() => setHospitals((current) => current.filter((item) => item._id !== hospital._id))).catch((e) => Alert.alert("Unable to delete", getApiErrorMessage(e))) }]); return <AdminAccess><AppScreen title="Hospital Management" subtitle="Maintain the hospitals and blood banks in your network."><Pressable onPress={() => { setEditing(null); setForm(blank); }} style={[styles.add, { backgroundColor: colors.accent }]}><Text style={styles.addText}>+ Add Hospital</Text></Pressable>{loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : hospitals.length === 0 ? <Surface><Text style={{ color: colors.muted }}>No hospitals added yet.</Text></Surface> : hospitals.map((hospital) => <Surface key={hospital._id} style={styles.row}><View style={[styles.icon, { backgroundColor: "#DBEAFE" }]}><Text style={{ color: "#2563EB", fontWeight: "900" }}>+</Text></View><View style={styles.copy}><Text style={[styles.name, { color: colors.ink }]}>{hospital.name}</Text><Text style={[styles.detail, { color: colors.muted }]}>{hospital.address}, {hospital.district}, {hospital.state}</Text><Text style={[styles.detail, { color: colors.muted }]}>{hospital.phone}</Text></View><View><Pressable onPress={() => { setEditing(hospital); setForm({ name: hospital.name, address: hospital.address, state: hospital.state, district: hospital.district, phone: hospital.phone, latitude: hospital.latitude, longitude: hospital.longitude }); }}><Text style={[styles.actionText, { color: "#2563EB" }]}>Edit</Text></Pressable><Pressable onPress={() => remove(hospital)}><Text style={[styles.actionText, { color: colors.accent }]}>Delete</Text></Pressable></View></Surface>)}<HospitalForm form={form} setForm={setForm} onSave={() => void save()} onClose={() => { setForm(null); setEditing(null); }} title={editing ? "Edit Hospital" : "Add Hospital"} /></AppScreen></AdminAccess>; }
function HospitalForm({ form, setForm, onSave, onClose, title }: { form: HospitalInput | null; setForm: (form: HospitalInput | null) => void; onSave: () => void; onClose: () => void; title: string }) { const colors = useThemeColors(); if (!form) return null; const set = (key: keyof HospitalInput, value: string) => setForm({ ...form, [key]: value }); return <Modal visible transparent animationType="slide"><View style={styles.backdrop}><Surface style={styles.modal}><Text style={[styles.modalTitle, { color: colors.ink }]}>{title}</Text>{([ ["name", "Hospital / Blood Bank Name"], ["address", "Address"], ["state", "State"], ["district", "District"], ["phone", "10-digit phone" ]] as const).map(([key, label]) => <TextInput key={key} placeholder={label} placeholderTextColor={colors.muted} value={form[key] as string} onChangeText={(value) => set(key, value)} keyboardType={key === "phone" ? "phone-pad" : "default"} style={[styles.input, { borderColor: colors.border, color: colors.ink }]} />)}<Pressable onPress={onSave} style={[styles.save, { backgroundColor: colors.accent }]}><Text style={styles.addText}>Save Hospital</Text></Pressable><Pressable onPress={onClose}><Text style={[styles.cancel, { color: colors.muted }]}>Cancel</Text></Pressable></Surface></View></Modal>; }
const styles = StyleSheet.create({ add: { alignItems: "center", borderRadius: 11, marginTop: spacing.lg, padding: 13 }, addText: { color: "#FFF", fontSize: 14, fontWeight: "900" }, loader: { marginTop: spacing.xl }, row: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm }, icon: { alignItems: "center", borderRadius: 10, height: 36, justifyContent: "center", width: 36 }, copy: { flex: 1 }, name: { fontSize: 14, fontWeight: "900" }, detail: { fontSize: 12, lineHeight: 18, marginTop: 2 }, actionText: { fontSize: 12, fontWeight: "900", padding: 4, textAlign: "right" }, backdrop: { backgroundColor: "#0F172A99", flex: 1, justifyContent: "flex-end", padding: spacing.md }, modal: { gap: spacing.sm }, modalTitle: { fontSize: 18, fontWeight: "900", marginBottom: spacing.sm }, input: { borderRadius: 10, borderWidth: 1, fontSize: 14, padding: 11 }, save: { alignItems: "center", borderRadius: 10, marginTop: spacing.sm, padding: 12 }, cancel: { alignSelf: "center", fontWeight: "800", padding: 8 } });
