import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";

import { AdminAccess } from "../../src/components/AdminAccess";
import { AppScreen, SectionTitle, Surface } from "../../src/components/AppScreen";
import { adminService } from "../../src/services/adminService";
import { emergencyService } from "../../src/services/emergencyService";
import { spacing } from "../../src/theme/spacing";
import { useThemeColors } from "../../src/theme/useThemeColors";
import type { EmergencyRequest } from "../../src/types/userFeatures";
import { getApiErrorMessage } from "../../src/utils/apiError";

export default function AdminRequestsScreen() {
  const colors = useThemeColors(); const [requests, setRequests] = useState<EmergencyRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [filter, setFilter] = useState<"Pending" | "All">("Pending");
  const load = useCallback(async () => { await Promise.resolve(); setLoading(true); try { setRequests(await emergencyService.list()); setError(null); } catch (e) { setError(getApiErrorMessage(e)); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const action = async (id: string, type: "approve" | "reject") => { setBusy(`${id}-${type}`); try { const updated = type === "approve" ? await adminService.approveRequest(id) : await adminService.rejectRequest(id); setRequests((current) => current.map((item) => item._id === id ? updated : item)); } catch (e) { Alert.alert("Unable to update request", getApiErrorMessage(e)); } finally { setBusy(null); } };
  const visible = filter === "Pending" ? requests.filter((item) => item.status === "Pending") : requests;
  return <AdminAccess><AppScreen title="Emergency Requests" subtitle="Review and respond to requests submitted by BloodLink users."><View style={styles.filters}><Filter label="Pending" active={filter === "Pending"} onPress={() => setFilter("Pending")} /><Filter label="All Requests" active={filter === "All"} onPress={() => setFilter("All")} /></View><SectionTitle>{filter === "Pending" ? "Needs attention" : "All requests"}</SectionTitle>{loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : error ? <Surface><Text style={{ color: colors.warning }}>{error}</Text><Pressable onPress={() => void load()}><Text style={[styles.retry, { color: colors.accent }]}>Retry</Text></Pressable></Surface> : visible.length === 0 ? <Surface><Text style={{ color: colors.muted }}>No {filter.toLowerCase()} requests.</Text></Surface> : visible.map((request) => <RequestCard key={request._id} request={request} busy={busy} onAction={action} />)}</AppScreen></AdminAccess>;
}
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { const colors = useThemeColors(); return <Pressable onPress={onPress} style={[styles.filter, { backgroundColor: active ? colors.accent : colors.surfaceMuted }]}><Text style={{ color: active ? "#FFF" : colors.muted, fontSize: 12, fontWeight: "800" }}>{label}</Text></Pressable>; }
function RequestCard({ request, busy, onAction }: { request: EmergencyRequest; busy: string | null; onAction: (id: string, type: "approve" | "reject") => Promise<void> }) { const colors = useThemeColors(); const requester = typeof request.requestBy === "string" ? "BloodLink user" : request.requestBy.name; const statusColor = request.status === "Approved" ? colors.success : request.status === "Rejected" ? colors.accent : "#D97706"; return <Surface style={styles.card}><View style={styles.cardHead}><View style={[styles.group, { backgroundColor: "#FEE2E2" }]}><Text style={{ color: colors.accent, fontWeight: "900" }}>{request.bloodGroup}</Text></View><View style={styles.copy}><Text style={[styles.hospital, { color: colors.ink }]}>{request.hospital}</Text><Text style={[styles.detail, { color: colors.muted }]}>{requester} · {request.district}, {request.state}</Text></View><Text style={[styles.status, { color: statusColor }]}>{request.status}</Text></View><Text style={[styles.detail, { color: colors.muted }]}>{request.unitsRequired} unit{request.unitsRequired === 1 ? "" : "s"} · {request.address}</Text><Text style={[styles.detail, { color: colors.muted }]}>Contact: {request.contactNumber}</Text>{request.status === "Pending" ? <View style={styles.actions}><Pressable disabled={busy !== null} onPress={() => void onAction(request._id, "approve")} style={[styles.approve, { backgroundColor: colors.success }]}><Text style={styles.buttonText}>{busy === `${request._id}-approve` ? "Approving…" : "✓ Approve"}</Text></Pressable><Pressable disabled={busy !== null} onPress={() => void onAction(request._id, "reject")} style={[styles.reject, { borderColor: "#FCA5A5" }]}><Text style={{ color: colors.accent, fontWeight: "900" }}>{busy === `${request._id}-reject` ? "Rejecting…" : "Reject"}</Text></Pressable></View> : null}</Surface>; }
const styles = StyleSheet.create({ filters: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.lg }, filter: { borderRadius: 999, paddingHorizontal: 13, paddingVertical: 8 }, loader: { marginTop: spacing.xl }, retry: { fontWeight: "800", marginTop: spacing.md }, card: { gap: 8 }, cardHead: { alignItems: "center", flexDirection: "row", gap: spacing.sm }, group: { alignItems: "center", borderRadius: 10, height: 38, justifyContent: "center", width: 38 }, copy: { flex: 1 }, hospital: { fontSize: 14, fontWeight: "900" }, detail: { fontSize: 12, lineHeight: 18 }, status: { fontSize: 11, fontWeight: "900" }, actions: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.sm }, approve: { alignItems: "center", borderRadius: 9, flex: 1, padding: 10 }, reject: { alignItems: "center", borderRadius: 9, borderWidth: 1, flex: 1, padding: 10 }, buttonText: { color: "#FFF", fontWeight: "900" } });
