import * as DocumentPicker from "expo-document-picker";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AdminAccess } from "../../src/components/AdminAccess";
import { AppScreen, SectionTitle, Surface } from "../../src/components/AppScreen";
import { InventoryStatus } from "../../src/components/InventoryStatus";
import { adminService } from "../../src/services/adminService";
import { spacing } from "../../src/theme/spacing";
import { useThemeColors } from "../../src/theme/useThemeColors";
import type { AvailabilityThresholds, InventoryItem, InventoryUpload } from "../../src/types/userFeatures";
import { getApiErrorMessage } from "../../src/utils/apiError";

export default function InventoryScreen() {
  const colors = useThemeColors(); const [inventory, setInventory] = useState<InventoryItem[]>([]); const [thresholds, setThresholds] = useState<AvailabilityThresholds | null>(null); const [history, setHistory] = useState<InventoryUpload[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busyId, setBusyId] = useState<string | null>(null); const [historyOpen, setHistoryOpen] = useState(false);
  const load = useCallback(async () => { await Promise.resolve(); setLoading(true); try { const [items, levels, uploads] = await Promise.all([adminService.getInventory(), adminService.getThresholds(), adminService.getUploadHistory()]); setInventory(items); setThresholds(levels); setHistory(uploads); setError(null); } catch (e) { setError(getApiErrorMessage(e)); } finally { setLoading(false); } }, []);
  // `load` defers its first state write and synchronizes live server data on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  const total = useMemo(() => inventory.reduce((sum, item) => sum + item.units, 0), [inventory]);
  const upload = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["text/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/pdf"], copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; const ext = asset.name.split(".").pop()?.toLowerCase(); if (!ext || !["csv", "xls", "xlsx", "pdf"].includes(ext)) { Alert.alert("Unsupported file", "Choose a CSV, Excel, or PDF inventory file."); return; } setBusyId("upload"); try { const items = await adminService.uploadInventory(asset, "merge"); setInventory(items); const uploads = await adminService.getUploadHistory(); setHistory(uploads); Alert.alert("Inventory updated", "The file was validated and merged into your stock."); } catch (e) { Alert.alert("Upload failed", getApiErrorMessage(e)); } finally { setBusyId(null); } };
  const adjust = async (item: InventoryItem, delta: number) => { setBusyId(item._id); try { const updated = await adminService.adjustInventory(item._id, delta); setInventory((items) => items.map((current) => current._id === updated._id ? updated : current)); } catch (e) { Alert.alert("Update failed", getApiErrorMessage(e)); } finally { setBusyId(null); } };
  return <AdminAccess><AppScreen title="Blood Inventory" subtitle="Track and update stock levels for every blood group.">
    <Surface style={styles.header}><View><Text style={[styles.headerTitle, { color: colors.ink }]}>Blood Bank Inventory</Text><Text style={[styles.headerText, { color: colors.muted }]}>{total} Total Units · Last updated from live data</Text></View><Pressable onPress={() => void upload()} disabled={busyId === "upload"} style={[styles.upload, { backgroundColor: colors.accent }]}>{busyId === "upload" ? <ActivityIndicator color="#FFF" /> : <Text style={styles.uploadText}>⇧ Upload File</Text>}</Pressable></Surface>
    <Pressable onPress={() => setHistoryOpen(true)}><Text style={[styles.historyButton, { color: colors.accent }]}>◷ Upload History ({history.length})</Text></Pressable>
    {loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : error ? <Surface><Text style={{ color: colors.warning }}>{error}</Text><Pressable onPress={() => void load()}><Text style={[styles.retry, { color: colors.accent }]}>Retry</Text></Pressable></Surface> : <><SectionTitle>Available stock</SectionTitle>{inventory.map((item) => <Surface key={item._id} style={styles.row}><View style={styles.rowTop}><View style={[styles.group, { backgroundColor: groupColor(item.bloodGroup) }]}><Text style={styles.groupText}>● {item.bloodGroup}</Text></View><Text style={[styles.units, { color: item.units === 0 ? colors.accent : colors.ink }]}>{item.units} <Text style={[styles.unitLabel, { color: colors.muted }]}>units</Text></Text></View><InventoryStatus units={item.units} thresholds={thresholds} /><View style={styles.actions}><Pressable disabled={busyId === item._id} onPress={() => void adjust(item, 1)} style={[styles.add, { borderColor: "#86EFAC" }]}><Text style={{ color: "#15803D", fontWeight: "800" }}>+ Add</Text></Pressable><Pressable disabled={busyId === item._id || item.units === 0} onPress={() => void adjust(item, -1)} style={[styles.remove, { borderColor: "#FCD34D" }]}><Text style={{ color: "#B45309", fontWeight: "800" }}>− Remove</Text></Pressable><ManualEdit item={item} onSave={async (units) => { setBusyId(item._id); try { const updated = await adminService.updateInventory(item._id, units); setInventory((items) => items.map((current) => current._id === updated._id ? updated : current)); } finally { setBusyId(null); } }} /></View></Surface>)}</>}
    <Modal visible={historyOpen} animationType="slide" transparent onRequestClose={() => setHistoryOpen(false)}><View style={styles.modalBackdrop}><Surface style={styles.modal}><Text style={[styles.modalTitle, { color: colors.ink }]}>Upload History</Text>{history.length === 0 ? <Text style={{ color: colors.muted }}>No inventory uploads yet.</Text> : history.map((upload) => <View key={upload._id} style={[styles.historyRow, { borderColor: colors.border }]}><Text style={[styles.fileName, { color: colors.ink }]}>{upload.fileName}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{upload.summary.validRecords} records · {upload.summary.unitsAdded} units · {upload.mode}</Text></View>)}<Pressable onPress={() => setHistoryOpen(false)} style={[styles.close, { backgroundColor: colors.accent }]}><Text style={styles.uploadText}>Close</Text></Pressable></Surface></View></Modal>
  </AppScreen></AdminAccess>;
}
function ManualEdit({ item, onSave }: { item: InventoryItem; onSave: (units: number) => Promise<void> }) { const colors = useThemeColors(); const [open, setOpen] = useState(false); const [value, setValue] = useState(String(item.units)); return <><Pressable onPress={() => setOpen(true)} style={[styles.edit, { borderColor: colors.border }]}><Text style={[{ color: colors.muted, fontWeight: "800" }]}>Edit</Text></Pressable><Modal visible={open} transparent animationType="fade"><View style={styles.modalBackdrop}><Surface style={styles.modal}><Text style={[styles.modalTitle, { color: colors.ink }]}>Set {item.bloodGroup} units</Text><TextInput value={value} onChangeText={setValue} keyboardType="number-pad" style={[styles.input, { borderColor: colors.border, color: colors.ink }]} /><Pressable onPress={() => void onSave(Math.max(0, Number(value) || 0)).then(() => setOpen(false))} style={[styles.close, { backgroundColor: colors.accent }]}><Text style={styles.uploadText}>Save units</Text></Pressable><Pressable onPress={() => setOpen(false)}><Text style={[styles.cancel, { color: colors.muted }]}>Cancel</Text></Pressable></Surface></View></Modal></>; }
function groupColor(group: string) { if (group.startsWith("A")) return "#FEE2E2"; if (group.startsWith("B") && !group.startsWith("AB")) return "#DBEAFE"; if (group.startsWith("AB")) return "#F3E8FF"; return "#D1FAE5"; }
const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, headerTitle: { fontSize: 15, fontWeight: "900" }, headerText: { fontSize: 11, marginTop: 4 }, upload: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 10 }, uploadText: { color: "#FFF", fontSize: 12, fontWeight: "900" }, historyButton: { fontSize: 13, fontWeight: "800", marginTop: spacing.md }, loader: { marginTop: spacing.xl }, retry: { fontWeight: "800", marginTop: spacing.md }, row: { gap: spacing.md }, rowTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, group: { borderRadius: 9, paddingHorizontal: 9, paddingVertical: 7 }, groupText: { color: "#334155", fontSize: 13, fontWeight: "900" }, units: { fontSize: 21, fontWeight: "900" }, unitLabel: { fontSize: 11, fontWeight: "400" }, actions: { flexDirection: "row", gap: 8 }, add: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, remove: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, edit: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, modalBackdrop: { alignItems: "center", backgroundColor: "#0F172A99", flex: 1, justifyContent: "center", padding: spacing.lg }, modal: { alignSelf: "stretch", gap: spacing.md }, modalTitle: { fontSize: 17, fontWeight: "900" }, historyRow: { borderBottomWidth: 1, gap: 3, paddingBottom: 10 }, fileName: { fontSize: 13, fontWeight: "800" }, close: { alignItems: "center", borderRadius: 10, marginTop: spacing.sm, padding: 12 }, input: { borderRadius: 10, borderWidth: 1, fontSize: 18, padding: 12 }, cancel: { alignSelf: "center", fontWeight: "800", padding: 8 } });
